### ISSUE TITLE
Under the light theme, some toolbars are transparent.

### ISSUE THREAD

**Issue by x-jiaxin** [gerryhjs/gerry-themes#14]
![image](https://github.com/gerryhjs/gerry-themes/assets/86563678/534613bb-e5ee-4109-9bdf-b0eceb0fcd93)
![image](https://github.com/gerryhjs/gerry-themes/assets/86563678/4689d826-a316-4ae7-9db8-ee9ad2ee49d0)

**Comment by x-jiaxin** [comment]
IDE:CLion 2023.2.2
Theme: sky

**Comment by gerryhjs** [comment]
Hi. This look like a color bug with new UI, because plugin didn't change icons color in themes. 
I saw similar ticket on youtrack: https://youtrack.jetbrains.com/issue/IDEA-307187/EJB-Icon-stays-gray-when-highlighted-new-UI Could you switch to "Intelij Light" and check if icon is same gray color.

**Comment by gerryhjs** [comment]
Hi. This look like a color bug with new UI, because plugin didn't change icons color in themes.
Could you switch to "Intelij Light" and check if icon is same gray color.

**Comment by x-jiaxin** [comment]
Okay, thank you.

**Comment by gerryhjs** [comment]
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/386be322-d5ab-4f10-a246-5fb2e6010ee2)
I check this issue with default light theme has same problem, the icon color is hard to see. I will report this on youtrack later.

**Comment by gerryhjs** [comment]
This issue is fixed in latest version. Please try after upgrade :)

**Comment by gerryhjs** [comment]
This issue is fixed in latest plugin version. Please try after upgrade plugin. :)
