### ISSUE TITLE
Font Color For GitHub Copilot Chat is Not Visible For Theme Gerry + Aurora (Pro)

### ISSUE THREAD

**Issue by M0hamedkhalid** [gerryhjs/gerry-themes#23]
![image](https://github.com/gerryhjs/gerry-themes/assets/29782997/89f860c8-df28-4893-9c21-a78127a70cc8)

**Comment by gerryhjs** [comment]
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/340220c8-a2c3-4bf1-b328-ab942c7a7b87)
I could not reproduce this issue with or GitHub Copilot plugin ( I don't have acces with GitHub Copilot chat windows, so I use GitHub Copilot windows to reproduce this issue).

Please let me know if you are using Gerry Themes Pro with other third party plugin such as "Material Theme UI", and try to disable Material Theme UI and check again.

Thanks.

**Comment by gerryhjs** [comment]
I could not reproduce this issue with or GitHub Copilot plugin. 
Please let me know if you are using Gerry Themes Pro with Material Theme UI, and try to disable Material Theme UI and check again. If issue still exists, please paste IDE and plugins info in "Help- About".

Thanks.

**Comment by M0hamedkhalid** [comment]
The IDE I am using is Rider JetBrains Rider 2023.3, I tried to reproduce the issue again after disabling Material Theme UI and seems that solved it.
