### ISSUE TITLE
the "Run Configuration" menu button's color is too bright in light themes.

### ISSUE THREAD

**Issue by xyzpinecone** [gerryhjs/gerry-themes#25]
light themes are like:
<img width="384" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/12005965/c47776f1-0584-4077-b150-42e4c4173a6e">

and the built-in light theme is like:
<img width="428" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/12005965/155dd8e9-5bfb-4925-8fbe-cfbc56e8e78e">

dark themes are fine.

---
MacOS 14.2
Idea 2023.3.2

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/14 
→Which is caused by https://youtrack.jetbrains.com/issue/IDEA-323076/Incorrect-color-of-Icon-More-Actions-in-Run-Configuration-widget

**Comment by gerryhjs** [comment]
This issue is fixed in latest plugin version. Please try after upgrade plugin. :)
