### ISSUE TITLE
Hard to see inserting changes in Diffs using Darcula+

### ISSUE THREAD

**Issue by Khoulaiz** [gerryhjs/gerry-themes#27]
Hi!

I am using Garry+ Darcula and overall I am happy with it. What I am doing very often is checking changes to Git versions or local older version using the Diff View of IntelliJ. 
Having an inserting change on a changed line is currently very hard to see in Dark Mode.
It's #294436 on #205562, which is a slighter lighter green on green. 
Could you please make it more contrasty to spot the changes easier. I am currently switching it to a completely different base color to make it easy to spot, like #564B29 (but I am open for anything else). Just make it spotable and readable.
Would be nice if you consider this use case in your original color scheme so I don't need to customise it.

**Comment by gerryhjs** [comment]
Thanks for your feedback, I will consider adjusting DIFF_INSERTED background a bit contrast.  I check "#564B29" but it is not green so it may be a bit confused for a inserting color. Currently I plan to change "#294436" to a more contrast green similar to "#295836". Please check the eap version: https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by gerryhjs** [comment]
Thanks for your feedback, I will consider adjusting DIFF_INSERTED background a bit contrast. 
Please check the eap version: https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by gerryhjs** [comment]
before change:
![before](https://github.com/gerryhjs/gerry-themes/assets/45413498/95f11e63-2f6a-43bd-91d3-b38a7fee5a83)
after change:
![after](https://github.com/gerryhjs/gerry-themes/assets/45413498/2ad89b47-4f2b-4b2c-8bcb-95e81f765805)

**Comment by Khoulaiz** [comment]
Looks good for me. Thank you!
