### ISSUE TITLE
The problem with the color in the ide

### ISSUE THREAD

**Issue by dit7c1** [gerryhjs/gerry-themes#30]
Hi! I am creating an incident at your request.

1. The text under the carriage and the highlighted text, the practical one is no different (when the eyes are tired or the weather is sunny). In other words, it is unclear whether the text is highlighted or whether the text is under the carriage. The same problem with refactoring (for example, renaming a method or variable, or etc. it is unclear which part of the text is highlighted).
I fixed it like this:
Solarized Theme - go - Settings - Editor - Color Scheme - General - Code
-Identifier under caret - background = ECDFB6
-Identifier under caret (write)- background = ECDFB6
Aqua Theme - go - Settings - Editor - Color Scheme - General - Code
-Identifier under caret - background = D1F6D9
-Identifier under caret (write)- background = D1F6D9
Added a screenshot before and after for both themes.
At the top is the text under the caret, at the bottom is the highlighted text.

2. The problem with the horizontal scrollbar. The main background is missing and the color of the inactive scrollbar is different.
I took the color from the Scrollbar (marked with the number 3 and 4 in the screenshot) and set it to the Vertical Scrollbar (marked with the number 1 in the screenshot)
I fixed it like this:
Solarized Theme - go - Settings - Editor - Color Scheme - General - Editor - Vertical Scrollbar
-Thumb - background = C1CFCBFF
The background of the horizontal Scrollbar could not be fixed, because I did not find where to change the color. I think this is no longer changing in the ide itself.

3. As I wrote earlier, if you delete a parameter in the main method, and where this method is called, the number of arguments is greater (in other words, the number of arguments and parameters does not match), then usually this line is red, which immediately attracts attention, but you have it black (I did not pay attention at all that there is an error).
I didn't find where to change it.

In general, everything is fine, but there are moments)).
I also like Legacy format themes more, but there is only one light theme ((.

p.1 your
![1before1](https://github.com/gerryhjs/gerry-themes/assets/29520345/427d1422-d837-4a4c-ab35-fd963df22932)

p.1 my
![1after1](https://github.com/gerryhjs/gerry-themes/assets/29520345/7765f676-7984-4448-8b2b-c30fadd92565)

p.1 your
![2before2](https://github.com/gerryhjs/gerry-themes/assets/29520345/37fb5745-6c9b-4d8a-b826-7f10215bcdf8)

p.1 my
![2after2](https://github.com/gerryhjs/gerry-themes/assets/29520345/2279aa82-6fda-41e8-a82b-ad742109b98e)

p.2
![scrollbar1](https://github.com/gerryhjs/gerry-themes/assets/29520345/22e6074d-9f50-4759-8d5f-6efd1f4c445e)
![scrollbar2](https://github.com/gerryhjs/gerry-themes/assets/29520345/6db1d1f1-1850-4460-a051-e2a8d28f7aff)

p.3
![problem](https://github.com/gerryhjs/gerry-themes/assets/29520345/fe98c197-0baa-4586-8953-5a3f0192e3f4)

With respect to your work!

**Comment by dit7c1** [comment]
horizontal scroll bar:
I am also using the latest version of IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Perhaps this is a feature of mac OS or the development environment itself?! In any case, I like the Aqua theme more, the lack of background is not so noticeable here.

I'll check the plugin a little later, finish the work tasks...
Thank you!

**Comment by gerryhjs** [comment]
I check screenshot again and found maybe I have misunderstanding the last issue of "error text", I thought you are talking about "error text with dialog" as my screenshot. I will check if plugin could customized this font color.

**Comment by gerryhjs** [comment]
For error font issue: I check the keys with internal mode and didn't find a valid attribute could modified by plugin yet.
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/b0046cd2-9c85-40a6-9c54-7455592a48d2)

For scrollbar issue, I have found a way to customized background to transport, but I am not sure if it could works. 
It will included in next release later.

**Comment by gerryhjs** [comment]
I check screenshot again and found maybe I have misunderstanding the last issue of "error text", I thought you are talking about "error text with dialog" as my screenshot. I will check if plugin could customized this font color.

1. For error font issue: I check the keys with internal mode and didn't find a valid attribute could modified by plugin yet. >.<
2. For scrollbar issue, I have found a way to customized background to transport for mac by "ScrollBar.Mac.background", 
but I am not sure if it could works.  
It will included in next release later.

**Comment by gerryhjs** [comment]
Preview:
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/08992393-3bb9-4c79-a174-a0e36ad31fd6)
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/1b1521de-333a-47b3-ae70-9d960c063c69)

**Comment by gerryhjs** [comment]
The partially changes have been updated to next release (expect to be approved within two business days). 
If you have any futher suggestions, please feel free to reply under this issue.

Thanks again for support Gerry Themes Pro~

**Comment by gerryhjs** [comment]
@dit7c1 If "ScrollBar.Mac.background doesn't work, I think is possible a bug with IDE. Could you check with "Inetlij Light" or some else light themes you used and check if the scrollbar background is not white on your computuer?

**Comment by gerryhjs** [comment]
Also you could help me by check the color attribute in internal mode if possible:
1.Select Help | Edit Custom Properties.... 
Add the line shown below to the idea.properties file:
idea.is.internal=true
2. Restart IDE, then press "Ctr + alt + CLick" to scrollbar area and provide a screenshot with the result.

**Comment by dit7c1** [comment]
@gerryhjs Hi!
I checked on a dark (native) theme, the background is dark. On a light (white) one, the background is expected to be white)))
The screenshot is attached below
![IntelliJ IDEA000019](https://github.com/gerryhjs/gerry-themes/assets/29520345/845f9caa-6682-4b5e-a274-7b7eb51d316f)


I also did ctrl+alt+click, tried to change the background there, but it changes globally.
![IntelliJ IDEA000023](https://github.com/gerryhjs/gerry-themes/assets/29520345/5a798249-32b0-4d46-87f3-e27e7933baa0)

**Comment by dit7c1** [comment]
another point, in light themes there is a problem with the color of regular expressions, they merge, it seems that it is a solid green color

![IntelliJ IDEA000025](https://github.com/gerryhjs/gerry-themes/assets/29520345/61485d10-fb48-4742-9eac-cbe359f05b85)

**Comment by gerryhjs** [comment]
@dit7c1 Seems there is not a valid key for "scrollbar bacground" currently based on internal result. (( 
As for Regex, I will consider change it to a better contrast color. This seems a good catch, thanks for feedback. 👍

**Comment by gerryhjs** [comment]
> another point, in light themes there is a problem with the color of regular expressions, they merge, it seems that it is a solid green color
> 
> ![IntelliJ IDEA000025](https://private-user-images.githubusercontent.com/29520345/312738812-61485d10-fb48-4742-9eac-cbe359f05b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDMzMTUsIm5iZiI6MTcxMDQwMzAxNSwicGF0aCI6Ii8yOTUyMDM0NS8zMTI3Mzg4MTItNjE0ODVkMTAtZmI0OC00NzQyLTllYWMtY2JlMzU5ZjA1Yjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MzUzNGQwNDVhZTUzMjIxOTFkZTEyMjczNjk1Y2ViN2ZkMzFlMGE4OWJkZDExNGE1MmEyNDU4Nzg1YTI1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PAnTWBBTwnPntzcZDHBei5p-N0h3-zp2YHgfsbFqtew)
> 
> this looks good in the screenshot as the text is large, but if you zoom out, the color difference will no longer be visible.

Please check latest EAP versions:
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by dit7c1** [comment]
I installed it, but:
I didn't see the difference ((

here is a screenshot from the (native) light theme from jetbrains
![IntelliJ IDEA000027](https://github.com/gerryhjs/gerry-themes/assets/29520345/4c2ba8be-47ee-4dbe-873a-2e60a973490f)


and here's your screenshot
![IntelliJ IDEA000029](https://github.com/gerryhjs/gerry-themes/assets/29520345/57edf16d-d55d-4e53-9276-cb5b4b461ed6)


maybe I'm inattentive, but I haven't figured out what's changed yet))

**Comment by gerryhjs** [comment]
Did you try "restore to default"? I changed regex color (and similar colors) from #106068 to #105088.

**Comment by gerryhjs** [comment]
Screenshot for EAP:
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/8f4ea83d-8d2d-4e70-9380-b40a781b8f28)

**Comment by gerryhjs** [comment]
I uploaded a new eap version with darker blue regex: (2023.1.0314-EAP2)
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/adc615eb-0586-47f1-a595-c4f22fd612b4)

**Comment by gerryhjs** [comment]
I uploaded a new eap version with darker blue regex: (2023.1.0314-EAP2)
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by gerryhjs** [comment]
I will use regex color for light themes from default light themes.
But I check the default light themes regex color is "#0037A6" not "174BE6". This is a bit confused me if I get correct point.

**Comment by gerryhjs** [comment]
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/fe473690-f309-46c9-a5ee-2b617ce8b535)

**Comment by gerryhjs** [comment]
The changes with colors → "#174BE6" has upload to EAP as you wish. Please check if it is better now.

**Comment by gerryhjs** [comment]
I thought I agree with color your suggested, the regex looks more clear now in light themes.
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/c4d8d8b6-80ee-41d4-ab2a-8675fa630b21)

**Comment by dit7c1** [comment]
I've updated it.
Yes, it's much better that way).
The main thing is that others like it)).
Anyway, you now know the bottlenecks.
