### ISSUE TITLE
Editor Tab color should not follow the theme color

### ISSUE THREAD

**Issue by Nasller** [gerryhjs/gerry-themes#34]
When I set the option in File Colors and view the editor tab, the colors are overwritten by the theme color.
![image](https://github.com/gerryhjs/gerry-themes/assets/26132153/ed206918-b0a2-4507-8309-fdbea5c77c8d)
![image](https://github.com/gerryhjs/gerry-themes/assets/26132153/ef30994d-3216-4fc3-bc1f-c606f42d6c3d)

IDEA-Dark theme is correct
![image](https://github.com/gerryhjs/gerry-themes/assets/26132153/a05eb19d-f655-4e48-beb2-22d5dbb780d6)

**Comment by gerryhjs** [comment]
Fixed. Please check EAP here:
Gerry Themes: https://plugins.jetbrains.com/plugin/18922-gerry-themes/versions/eap
or Gerry Themes Pro:
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap

**Comment by Nasller** [comment]
Great!
