### ISSUE TITLE
Different tag color for Web tags and Client/Server Components

### ISSUE THREAD

**Issue by LouisLecouturier** [gerryhjs/gerry-themes#38]
It would be nice to have different colors for Web Components

And to also differentiate Client/Server components like in the basic JetBrains Theme (like in example)

<img width="857" alt="Screenshot 2024-07-24 at 14 18 04" src="https://github.com/user-attachments/assets/4331bac9-7fbd-4206-9cf4-62231d26dbdf">

**Comment by gerryhjs** [comment]
Thanks for your feedback. Would you like to share screenshot code if possible. I will check that.

**Comment by LouisLecouturier** [comment]
Sure, same piece of code with Gerry's Violet

<img width="636" alt="image" src="https://github.com/user-attachments/assets/d21ddd19-ac80-470b-8605-5a4d41fa833c">

**Comment by gerryhjs** [comment]
Could your paste the code text :)  Just part of this code is enough.

**Comment by gerryhjs** [comment]
I think I found the custom tag ("Server"). But I didn't find out how to deal with "Button" tag. I will check with it in IDE later.

**Comment by LouisLecouturier** [comment]
### Client component
```jsx
"use client"

export const Client = () => {
return <div>Client</div>
}
```

### Server component

```jsx
export const Server = () => {
return <div>Server</div>
}
```



### Test script
```jsx
import { Client } from "./client.jsx"
import { Server } from "./server.jsx"


export const Test = () => {

return (
<div>
    <Client/>
    <Server/>
</div>

)

}
<div>
          <div>
            <PageTitle className={'lg:text-5xl w-fit'}>Good to see you !</PageTitle>
            <Text>Sign in or sign up to access the app !</Text>
          </div>
          <form
            action={async () => {
              'use server';
              await signIn('google', { callbackUrl: '/dashboard' });
            }}
          >
            <Button
              type={'submit'}
              style={'outlined'}
              color={'plain'}
              icon={<GoogleLogo className={'size-6'} />}
            >
              Sign in with Google
            </Button>
          </form>
        </div>
```



Should do the job ;)

**Comment by gerryhjs** [comment]
I check the Test script in IDE with default themes, the colors of Page Title and Button keywords are same color.
![image](https://github.com/user-attachments/assets/5162dea7-11ac-4aee-9c85-6da28a98587a)
Gerry Violet Modified:
![image](https://github.com/user-attachments/assets/7e4b1e38-3a74-43a6-89d8-a1ee41f59678) 

I will upgrade an EAP version later.

**Comment by LouisLecouturier** [comment]
Beautiful :)

Yeah I think this is specific when there is a NextJS config or something...

**Comment by gerryhjs** [comment]
Completed. Please check EAP version here:
Gerry Themes: 
https://plugins.jetbrains.com/plugin/18922-gerry-themes/versions/eap
or Gerry Themes Pro:
https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/eap
