### ISSUE TITLE
Error message unreadable

### ISSUE THREAD

**Issue by xianzheTM** [gerryhjs/gerry-themes#5]
![image](https://github.com/gerryhjs/gerry-themes/assets/25103583/ac5b2ba2-ab29-4d6e-a982-37b9e9a6e498)
plugin version: 2023.1.51
IDEA version: 2023.1.2

**Comment by gerryhjs** [comment]
Hi. Did restart IDE after switch between theme helps? And please describe how to reproduce this issue, thanks.

**Comment by gerryhjs** [comment]
I have reset those color to default. Please check these updates if they are solved:
https://plugins.jetbrains.com/files/18922/347273/GerryThemes.jar
https://plugins.jetbrains.com/files/19668/347271/GerryThemesPro.jar
