### ISSUE TITLE
Right-click menu spacing is small.

### ISSUE THREAD

**Issue by Mrz-zz** [gerryhjs/gerry-themes#6]
Hey, thank you very much for your efforts, which allow us to use such a beautiful theme.

There is currently an issue that I am not sure if it is intentionally designed or not yet compatible. The spacing between the menu bars displayed by right-clicking currently has obvious differences compared to the format under New UI.

Gerry Theme
<img width="295" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/4df5a36c-18f6-4ed3-93c2-ecfa05d98c6d">

Jetbrains New UI Dark
<img width="295" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/61a634e2-eb5c-4317-b534-f6b24fd90ee5">

I don't know if this optimization will be considered in future updates.

Best wishes!

**Comment by Mrz-zz** [comment]
The search panel also exists the problem.

Gerry Theme
<img width="739" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/24f07292-fb90-4794-9fb8-e488b8851c5d">

new UI 
<img width="739" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/23bd3782-4c8d-4dd4-aca8-40fb55e10e3d">

**Comment by gerryhjs** [comment]
Thanks for your kind words first. I couldn't reproduced issue on my IDE (IDEA-U 2023.1), but I'll investigate that.
Gerry Themes didn't change font size or width/height of component, so I think it is more likely a bug with new UI compatibility. Could you try to switch to "Darcula" (not Gerry Darcula) theme and check this issue again?
Also, I'll consider to set custom width value if it is necessary in future.

**Comment by gerryhjs** [comment]
Thanks for your kind words first. I couldn't reproduced issue on my IDE (IDEA-U 2023.1), but I'll investigate that.
Gerry Themes didn't change width of component, so I think it is likely a bug with new UI compatibility. Could you try to switch to "Darcula" (not Gerry Darcula) theme and check this issue again? Also, I'll consider to set custom width value if it is necessary, some similar adaptation may be implement after new UI released

**Comment by Mrz-zz** [comment]
hey, I tried what you said and here is the result(ideaU-2023.1):

<img width="1158" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/5455e521-aade-4970-bfd7-7eaca107645e">

**Comment by Mrz-zz** [comment]
It seems that only the font spacing of the default themes (Dark and Light), menu bar, and search bar will be significantly widened. In traditional themes, the font spacing still appears relatively narrow. In the default Darcula and IntelliJ Light themes, not only are the spacings of the menu bar and search bar narrow but also the left-side file list is narrow. The comparison can be seen below:

<img width="1494" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/36831062/d0ab5fb9-4578-474f-9719-5552033fb54d">

**Comment by gerryhjs** [comment]
I have raised a ticket in youtrack to discuss this issue with Jetbrains. Please provide information from IDE "About".

**Comment by Mrz-zz** [comment]
IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023
Licensed to xxx
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.gerryPurpleTheme (2023.1.55)
    org.jetbrains.kotlin (231-1.9.0-release-358-IJ8770.65)
    izhangzhihao.rainbow.brackets (2023.3.2)

Kotlin: 231-1.9.0-release-358-IJ8770.65

**Comment by gerryhjs** [comment]
Please try the latest version for Gerry Themes and check if width looks better now. https://plugins.jetbrains.com/plugin/download?rel=true&updateId=358475

**Comment by gerryhjs** [comment]
Please try eap for Gerry Themes and check if width looks better now: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=358475

**Comment by Mrz-zz** [comment]
I tried the new version and it is the same as the default theme. Thank you!
