### ISSUE TITLE
Gerry Oceanic theme error

### ISSUE THREAD

**Issue by lingyufei** [gerryhjs/gerry-themes#8]
<img width="2560" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/49775184/ae43fe02-7c8e-4566-a178-6b84f1640ce2">

When I use the Gerry Oceanic theme, the editor components will be white.
I'm using IDEA 2023.2

**Comment by trungdlp-wolffun** [comment]
@lingyufei same problem with Dark theme

**Comment by gerryhjs** [comment]
Hi, I meet same problem when I enabled IDE Sync setting, but I checked the theme relation is okay. Seems it is a issue with IDE. Please check your related color scheme in setting if it is not correct please switch the color scheme mannually, the related scheme will be fixed next time when you swicth to same themes again.

**Comment by gerryhjs** [comment]
![image](https://github.com/gerryhjs/gerry-themes/assets/45413498/959b6a94-f9c8-4c0d-8caf-c0f497f47486)

**Comment by gerryhjs** [comment]
Hi, I meet same problem when I enabled IDE Sync setting, but I checked the theme relation is okay. Seems it is an issue with IDE. Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme. It will be marked as "Theme Default".

See screenshot:
<img width="1716" height="1022" alt="Image" src="https://github.com/user-attachments/assets/17ebf351-9962-4111-ba3f-e549287f8056" />

**Comment by gerryhjs** [comment]
Refer issue on YouTrack:
https://youtrack.jetbrains.com/issue/IDEA-325237

**Comment by gerryhjs** [comment]
Please let me know if this workaround works or not. If it still could not solved, I will reopen this issue and invisigated it later.

**Comment by trungdlp-wolffun** [comment]
@gerryhjs Thank for your supported. I was fixed issue with my IDE <3

**Comment by lostpebble** [comment]
On the latest update- all my Gerry themes are not applying to the actual code editor part...

![image](https://github.com/gerryhjs/gerry-themes/assets/1508863/1146fec6-a089-4ed6-b17a-63f379e24f89)

**Comment by gerryhjs** [comment]
PS: Last update add this workaround description since it is reported serval times, you could find same workaround in plugin description. I also contact with Jetbrains internally about this issue.
