### ISSUE TITLE
Legacy Darcula has incorrect coloring in the editor

### ISSUE THREAD

**Issue by rhysdh540** [gerryhjs/gerry-themes#9]
just updated to 2023.1.60 (regular plugin) and the legacy darcula theme looks like this:

<img width="1678" alt="image" src="https://github.com/gerryhjs/gerry-themes/assets/98863820/2a4d81fc-af3c-45c0-b2e4-40d62bcef0a2">

**Comment by gerryhjs** [comment]
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8

**Comment by rhysdh540** [comment]
Sorry! Didn’t see that. Thanks for the quick response!
